[package]
name = "needs_rebuild"
version = "1.0.0"
edition = "2024"

[dependencies]
filetime = "0.2"
glob = "0.3"
log = "0.4"
thiserror = "2.0.17"
walkdir = "2.5"

[dev-dependencies]
env_logger = "0.11.8"